# Generated by Django 4.2.1 on 2024-04-11 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acesso', '0001_initial'),
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativo.curso'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='papeis',
            field=models.ManyToManyField(blank=True, to='administrativo.papel'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
